name: Deploy Portfolio

on:
  push:
    branches:
      - main # O master, dependiendo de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias y hacer Build
        run: |
          bun install
          bun run build

      - name: Conectar a la red de Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Desplegar archivos al servidor
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/*' # Cambia 'dist' si tu framework usa otra carpeta (ej. 'build')
          target: '/var/www/html/portfolio' # La ruta donde Nginx leerá tu web
          strip_components: 1
